/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration options for AutoRecon scanner */
export interface AutoReconConfig {
  /** Configuration directory path containing TOML files */
  configDir: string
  /** Port scan profile to use (e.g., "default", "quick", "udp") */
  profile: string
  /** Number of targets to scan concurrently */
  concurrentTargets?: number
  /** Number of scans to run per target concurrently */
  concurrentScans?: number
  /** Output directory for scan results */
  outputDir: string
  /** Verbosity level (0-2) */
  verbosity?: number
  /** Heartbeat interval in seconds */
  heartbeatInterval?: number
  /** Additional nmap arguments */
  nmapExtra?: string
}
/** Detected service from port scanning */
export interface DetectedService {
  /** Protocol (tcp/udp) */
  protocol: string
  /** Port number */
  port: number
  /** Service name */
  service: string
  /** Optional version information */
  version?: string
}
/** Scan target result */
export interface ScanResult {
  /** Target address */
  address: string
  /** Detected services */
  services: Array<DetectedService>
  /** Base directory for results */
  baseDir: string
  /** Scan duration in milliseconds */
  durationMs: number
  /** Whether the scan completed successfully */
  success: boolean
  /** Error message if scan failed */
  error?: string
}
/** Profile information */
export interface ProfileInfo {
  /** Profile name */
  name: string
  /** Number of scans in profile */
  scanCount: number
  /** List of scan names */
  scans: Array<string>
}
/** Initialize the module */
export declare function init(): void
/** Main AutoRecon scanner class */
export declare class AutoRecon {
  /** Create a new AutoRecon instance */
  constructor(config: AutoReconConfig)
  /**
   * Scan a single target
   *
   * This method takes a threadsafe callback function for command execution.
   * The callback will be called from a background thread.
   */
  scanTarget(address: string, executeCallback: (...args: any[]) => any): Promise<ScanResult>
  /** List available scan profiles */
  listProfiles(): Array<string>
  /** Get profile information */
  getProfileInfo(profileName: string): ProfileInfo | null
}
