/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Configuration options for AutoRecon scanner
 */
export interface AutoReconConfig {
  /** Configuration directory path containing TOML files */
  configDir: string
  /** Port scan profile to use (e.g., "default", "quick", "udp") */
  profile: string
  /** Number of targets to scan concurrently */
  concurrentTargets?: number
  /** Number of scans to run per target concurrently */
  concurrentScans?: number
  /** Output directory for scan results */
  outputDir: string
  /** Verbosity level (0-2) */
  verbosity?: number
  /** Heartbeat interval in seconds */
  heartbeatInterval?: number
  /** Additional nmap arguments */
  nmapExtra?: string
}

/**
 * Detected service from port scanning
 */
export interface DetectedService {
  /** Protocol (tcp/udp) */
  protocol: string
  /** Port number */
  port: number
  /** Service name */
  service: string
  /** Optional version information */
  version?: string
}

/**
 * Scan target result
 */
export interface ScanResult {
  /** Target address */
  address: string
  /** Detected services */
  services: Array<DetectedService>
  /** Base directory for results */
  baseDir: string
  /** Scan duration in milliseconds */
  durationMs: number
  /** Whether the scan completed successfully */
  success: boolean
  /** Error message if scan failed */
  error?: string
}

/**
 * Profile information
 */
export interface ProfileInfo {
  /** Profile name */
  name: string
  /** Number of scans in profile */
  scanCount: number
  /** List of scan names */
  scans: Array<string>
}

/**
 * Command output from execution callback
 */
export interface CommandOutput {
  /** Standard output */
  stdout: string
  /** Standard error */
  stderr: string
  /** Exit code (0 = success) */
  exitCode: number
  /** Duration of execution in milliseconds */
  durationMs: number
}

/**
 * Command execution callback function
 */
export type ExecuteCallback = (command: string) => Promise<CommandOutput>

/**
 * Tool availability check callback function
 */
export type CheckToolCallback = (toolName: string) => Promise<boolean>

/**
 * Main AutoRecon scanner class
 *
 * @example
 * ```typescript
 * import { AutoRecon } from '@autorecon/core';
 * import { exec } from 'child_process';
 * import { promisify } from 'util';
 *
 * const execAsync = promisify(exec);
 *
 * const scanner = new AutoRecon({
 *   configDir: './config',
 *   profile: 'default',
 *   outputDir: './results'
 * });
 *
 * const result = await scanner.scanTarget('192.168.1.1', async (cmd) => {
 *   const { stdout, stderr } = await execAsync(cmd);
 *   return {
 *     stdout,
 *     stderr,
 *     exitCode: 0,
 *     durationMs: 100
 *   };
 * });
 *
 * console.log(`Found ${result.services.length} services`);
 * ```
 */
export class AutoRecon {
  /**
   * Create a new AutoRecon instance
   *
   * @param config - Configuration options
   * @throws Error if configuration is invalid or profile not found
   */
  constructor(config: AutoReconConfig)

  /**
   * Scan a single target
   *
   * @param address - Target IP address or hostname
   * @param executeCallback - Callback function to execute commands
   * @returns Promise that resolves with scan results
   *
   * @example
   * ```typescript
   * const result = await autorecon.scanTarget('192.168.1.1', async (cmd) => {
   *   const { stdout, stderr } = await exec(cmd);
   *   return { stdout, stderr, exitCode: 0, durationMs: 100 };
   * });
   *
   * if (result.success) {
   *   console.log(`Scan completed in ${result.durationMs}ms`);
   *   result.services.forEach(svc => {
   *     console.log(`${svc.protocol}/${svc.port}: ${svc.service}`);
   *   });
   * }
   * ```
   */
  scanTarget(address: string, executeCallback: ExecuteCallback): Promise<ScanResult>

  /**
   * List available scan profiles
   *
   * @returns Array of profile names
   *
   * @example
   * ```typescript
   * const profiles = autorecon.listProfiles();
   * console.log('Available profiles:', profiles);
   * // Output: Available profiles: ['default', 'quick', 'udp']
   * ```
   */
  listProfiles(): Array<string>

  /**
   * Get profile information
   *
   * @param profileName - Name of the profile
   * @returns Profile information or null if not found
   *
   * @example
   * ```typescript
   * const info = autorecon.getProfileInfo('default');
   * if (info) {
   *   console.log(`Profile '${info.name}' has ${info.scanCount} scans`);
   *   info.scans.forEach(scan => console.log(`  - ${scan}`));
   * }
   * ```
   */
  getProfileInfo(profileName: string): ProfileInfo | null

  /**
   * Check if a tool is available in the system
   *
   * @param toolName - Name of the tool to check
   * @param checkCallback - Callback function to check tool availability
   * @returns Promise that resolves to true if tool is available
   *
   * @example
   * ```typescript
   * const hasNmap = await autorecon.checkTool('nmap', async (tool) => {
   *   try {
   *     await exec(`${tool} --version`);
   *     return true;
   *   } catch {
   *     return false;
   *   }
   * });
   *
   * if (!hasNmap) {
   *   console.error('nmap is not installed');
   * }
   * ```
   */
  checkTool(toolName: string, checkCallback: CheckToolCallback): Promise<boolean>
}

/**
 * Initialize the module
 */
export function init(): void
